# Generated by Django 4.1.2 on 2022-12-09 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('UTI', 'UTI'), ('UCI', 'UCI')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso', models.IntegerField()),
                ('orina', models.BooleanField()),
                ('deposicion', models.BooleanField()),
                ('tolerancia', models.CharField(max_length=50)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cama')),
                ('recienNacido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reciennacido')),
            ],
        ),
        migrations.AddField(
            model_name='cama',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sector'),
        ),
    ]
