# Generated by Django 4.1.2 on 2022-12-09 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucion',
            name='matrona',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Matronas'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Matronas', to=settings.AUTH_USER_MODEL),
        ),
    ]
