# Generated by Django 4.1.2 on 2022-12-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_reciennacido_padre_reciennacido_padres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciennacido',
            old_name='estado',
            new_name='deAlta',
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='alta',
            field=models.CharField(blank=True, choices=[('Traslado', 'Traslado'), ('A su domicilio', 'A su domicilio'), ('Fallecido', 'Fallecido')], max_length=50, null=True),
        ),
    ]
